// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { ExtendedDatabase } from './custom-types';

const SUPABASE_URL = "https://kcfsqlbixvxotjtddhhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtjZnNxbGJpeHZ4b3RqdGRkaGhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NDYzOTEsImV4cCI6MjA2MDAyMjM5MX0.8OsYfZcwY1T_LumiuPWV-Hbmq3UoTmvDI6UAkS3aITo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);